# List of symbols to scan - High Liquidity & Momentum focus
SYMBOLS = [
    'BTC/USDT',
    'ETH/USDT',
    'SOL/USDT',
    'BNB/USDT',
    'ADA/USDT',
    'XRP/USDT',
    'DOT/USDT',
    'LINK/USDT',
    'AVAX/USDT',
    'TRX/USDT',
    'LTC/USDT',
    'BCH/USDT',
    'DOGE/USDT',
    'NEAR/USDT',
    'ONDO/USDT',
    'SUSHI/USDT',
    'MATIC/USDT',
    'ARB/USDT',
    'OP/USDT',
    'TIA/USDT',
    'RNDR/USDT',
    'FET/USDT',
    'STX/USDT',
    'KAS/USDT',
    'INJ/USDT'
]
